#!/bin/sh

sList='0 0.1 0.2 0.3 0.4 0.5';
data='ce.txt';

for s in $sList; do \
  ./bsc.out $s;
  mv -f $data ce$s.txt;
  txtList="$txtList ce$s.txt";
done;

echo "Plotting data..."
octave -q bscPlot.m

rm -f $txtList
