#!/bin/sh
# start tclsh in next line \
exec tclsh "$0" "$@"

set data "ce.txt";
set sList [list 0 0.1 0.2 0.3 0.4 0.5];

foreach s $sList {
    exec {./bsc.out} $s;
    exec mv -f $data "ce${s}.txt";
    lappend txtList "ce${s}.txt";
}

exec octave -q bscPlot.m

foreach file $txtList {
    exec rm -f $file;
}
